[package]
name = "integration-tests"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
chrono.workspace = true
shared = { path = "../shared" }
sqlx.workspace = true
tokio.workspace = true
uuid.workspace = true

[dev-dependencies]
serial_test = "3"
